name: Release (Production version for A2 + GH Pages)
on: [workflow_dispatch]

jobs:
  validate-tag:
    name: Validate tag
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag to Build on
        run: |
          TAG="${{ github.ref_name }}"
          if [[ ! "$TAG" =~ ^v ]]; then
            echo "The workflow was run from an invalid ref."
            echo "Expected the ref name to start with a \"v\"."
            echo "If using the GitHub UI, please select a tag from the \"Use workflow from\" dropdown."
            exit 1
          fi

  run-tests:
    name: Run Tests
    needs: validate-tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 20.15.0
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Test
        run: npm run test

  build-pages:
    name: Build GitHub Page
    needs: run-tests
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 20.15.0
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --base=/abicus/

      - name: Upload Pages artefact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
